version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front:/usr/share/nginx/html:ro


  api:
    build:
      context: .
      dockerfile: ./api-Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    depends_on:
      - web
