version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front:/usr/share/nginx/html:ro
    # depends_on:
    #   - app
