version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  db:
    image: mariadb:latest
    env_file:
      - docker.env
    volumes:
      - ./back/db:/var/lib/mysql
